### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by richardfrost** [Depressurizer/Depressurizer#11]
Thanks for maintaining this project, I would cry if I had to manage things with the Steam client.

Anyway, I just switched over to your fork with a clean profile, but am still getting an error that I was seeing with Theo's version as well:

```Error updating from local files: The given key was not present in the dictionary.```

I see that every time I start the app. I couldn't find any logging settings to get more info out of it, but I am glad to help if there is anyway I can resolve that error message, thanks!

## Specifications
  - Version: 1.2.0.0
  - Operating System: Windows 10 (OS BUild 16299.192)

**Comment by mvegter** [comment]
@richardfrost Would you mind filling out the blanks.

**Comment by richardfrost** [comment]
I filled in the details, sorry I forgot to add those.

**Comment by mvegter** [comment]
@richardfrost Thanks, could you delete the appdata folder of Depressurizer:
- Windows Key + R
- Type: `%appdata%`
- Delete the Depressurizer folder

Also be sure to clear the folder containing Depressurizer. I just released [v1.2.0](https://github.com/mvegter/Depressurizer/releases/tag/v1.2.0) would you mind testing it with that version.

**Comment by richardfrost** [comment]
Alright, I did as instructed. I see that the new version created a `db.json`, but I still see the error message after I have specified my steam directory, updated HowLongToBeat, and then select my profile. It is right after I select my profile that it says:

```
Error
Error updating from local files:
The given key was not present in the dictionary.
```
  
  After I dismiss the error it proceeds to download the game list and then scrape the games.

I do have a fairly large library, so it's possible that has something to do with it?

**Comment by mvegter** [comment]
@richardfrost Could you repeat the previous instructions with this executable:
[Depressurizer-Debug.zip](https://github.com/mvegter/Depressurizer/files/1617965/Depressurizer-Debug.zip)

**Comment by mvegter** [comment]
@richardfrost Thank you, could you upload your `appinfo.vdf` file. You can find it in the Steam installation folder under the appcache folder.

Note: rename `appinfo.vdf` to `appinfo.vdf.txt` to be able to upload it to github.

**Comment by mvegter** [comment]
@richardfrost Could you repeat the previous instructions with this executable:
[Depressurizer-Debug.zip](https://github.com/mvegter/Depressurizer/files/1619316/Depressurizer-Debug.zip)

P.S. You can follow progress in branch: [patch/LocalConfig](https://github.com/mvegter/Depressurizer/tree/patch/LocalConfig)

**Comment by richardfrost** [comment]
Still had the error with the first debug app.

Here is my appinfo: https://gist.github.com/richardfrost/f6f88ecc60d26f098abc288374a31a00

The newest debug build ended up hanging a long time (but no error), but when it finally finished loading it failed to show anything (no games, etc).

**Comment by mvegter** [comment]
@richardfrost I messed up. I meant your `localconfig.vdf` instead of `appinfo.vdf`. But I got the data I needed from the thrown exceptions in sentry.

This version should fix it:
[Depressurizer-Debug.zip](https://github.com/mvegter/Depressurizer/files/1619935/Depressurizer-Debug.zip)

**Comment by richardfrost** [comment]
With the latest debug version it didn't get the error. Do you still want my `localconfig.vdf`?

**Comment by mvegter** [comment]
@richardfrost No thank you. In the sentry logs I found the data I needed. That is also one of the reasons why it was much slower.

Just to be sure:
- You cleared the appdata folder
- You either created a new folder and opened Depressurizer-Debug.exe or you cleaned the folder containing the previous debug version

**Comment by richardfrost** [comment]
Awesome, thanks for getting to this so quickly! Do you know when the next stable build will be released that has those fixes in it?

**Comment by mvegter** [comment]
@richardfrost I'm going to merge this into the dev any time now. I'm going to work on the standard categories (all, favorite, ...) right now. After I merge that one I will most likely make a new release.
